# GR Atom: Cloud IAM Security
# Version: 1.0
# Created: 2025-01-29

identity:
  id: "INFRA-CLOUD-IAM-001"
  name: "Cloud IAM Security"
  normalization:
    normalized_name: "cloud iam identity access management role policy"
    normalization_version: "1.0"
  aliases:
    - "클라우드 IAM"
    - "Identity and Access Management"
    - "권한 관리"

classification:
  domain: security
  type: component
  is_infrastructure: true
  abstraction_level: 3
  gr_coordinates:
    layer: "L7"
    zone: "Z2"
    function: "S1.1"
    atom_tags: ["AWS", "CLOUD", "IAM", "IMPACT"]

definition:
  what: |
    클라우드 IAM은 클라우드 리소스에 대한 접근을 관리하는 서비스로,
    사용자, 역할, 정책을 통해 권한을 제어한다.
  why: |
    과도한 권한은 침해 영향을 확대시킨다.
    최소 권한 원칙이 클라우드 보안의 핵심이다.
  how: |
    1. ID 체계 설계
    2. 역할 및 정책 정의
    3. 권한 할당
    4. 정기 감사 및 검토

relations:
  structural:
    is_a:
      - "GR-SEC-CONCEPT-001"

properties:
  technical:
    core_concepts:
      - name: "Principal"
        description: "작업 주체 (사용자, 서비스)"
      - name: "Resource"
        description: "접근 대상 (S3, EC2 등)"
      - name: "Action"
        description: "수행 작업 (읽기, 쓰기)"
      - name: "Policy"
        description: "권한 정의 문서"
      - name: "Role"
        description: "정책 모음, 임시 자격 증명"
    policy_types:
      - name: "Identity-based"
        description: "사용자/역할에 연결"
      - name: "Resource-based"
        description: "리소스에 직접 연결"
      - name: "Permission Boundary"
        description: "최대 권한 제한"
      - name: "SCP (AWS)"
        description: "조직 수준 제한"
    best_practices:
      - "루트 계정 사용 금지"
      - "MFA 필수"
      - "최소 권한 원칙"
      - "역할 기반 접근 제어"
      - "임시 자격 증명 사용"
      - "정기 권한 검토"
      - "미사용 자격 증명 제거"
      - "조건 키 활용"
    common_misconfigurations:
      - "와일드카드(*) 권한"
      - "인라인 정책 과다"
      - "루트 계정 사용"
      - "MFA 미설정"
      - "오래된 액세스 키"
    tools:
      - name: "AWS IAM Access Analyzer"
        purpose: "외부 접근 분석"
      - name: "Azure AD PIM"
        purpose: "권한 있는 ID 관리"
      - name: "GCP Policy Intelligence"
        purpose: "정책 분석"
    audit_checklist:
      - "미사용 사용자/역할"
      - "과도한 권한"
      - "MFA 상태"
      - "액세스 키 수명"
      - "크로스 계정 접근"

metadata:
  trust:
    source: official
    references:
      - "AWS IAM Best Practices"
      - "Azure AD Security"
    confidence: 1.0
    verified:
      status: verified
      date: 2025-01-29
      by: "GR System"
  temporal:
    created: 2025-01-29
    modified: 2025-01-29
    revision: 1
  security:
    sensitivity: public
  ai:
    embedding_text: |
      클라우드 IAM은 리소스 접근을 제어한다. 최소 권한, 역할 기반,
      MFA, 정기 검토가 핵심 원칙이다.
    search_keywords:
      - "IAM"
      - "권한 관리"
      - "클라우드 접근"
      - "정책"
    related_queries:
      - "AWS IAM"
      - "최소 권한"
      - "역할 기반"
